#!/bin/sh -x

# For crontab:
### Update bios demo
### 0 1 * * * bash /root/update_demo > /root/update_demo.log 2>&1

PATH="/bin:/usr/bin:/sbin:/usr/sbin"

[ -n "$VARIANT" ] || VARIANT="deploy"

# Download images, stop VM, preconfigure and finish at that
/root/ci-reset-virtual-machine.sh -b "$VARIANT" -m "demo" --deploy-only
cd /srv/libvirt/rootfs/demo/ || exit $?

echo "Populating custom configuration for the bios-demo VM"
#
# copy resolv.conf (demo has not OBS default, but ROZ LAB one)
#
cp -f /etc/resolv.conf ./etc/
echo bios-demo.roz53.lab.etn.com > ./etc/hostname
#
# create NUT config
#
cp /root/nut/* ./etc/nut

cat >./etc/nut/ups.conf.new << EOF
maxretry = 3

[ROZ.ePDU05]
	driver = snmp-ups
	port =  epdu05.roz53.lab.etn.com
	synchronous = yes

[ROZ.ePDU04]
	driver = snmp-ups
	port = epdu04.roz53.lab.etn.com
	synchronous = yes

[ROZ.UPS1]
	driver = netxml-ups
	port = http://nmc03.roz53.lab.etn.com

[UPS1-LAB]
        driver =  dummy-ups
        port =  UPS1-LAB.dev
        desc = "9PX-31-xml"

[UPS2-LAB]
        driver =  dummy-ups
        port =  UPS2-LAB.dev
        desc = "9PX-31-xml"

[ePDU1-LAB]
        driver =  dummy-ups
        port = ePDU1-LAB.dev
        desc = "epdu-marlin-ma-snmp"

[ePDU2-LAB]
        driver =  dummy-ups
        port = ePDU2-LAB.dev
        desc = "epdu-marlin-ma-snmp"
EOF

#
# Dump database from bios-rc-demo
#
[ -n "`ssh bios@bios-rc-demo.roz53.lab.etn.com echo ahoj`" ] && \
    ssh bios@bios-rc-demo.roz53.lab.etn.com mysqldump -u root box_utf8 > mysqldump

#
# Populate bios-demo database from project defaults and
# if available - override from replica of bios-rc-demo
cat << EOF | chroot . /bin/bash
/usr/lib/mysql/rcmysql start
wget -O - "http://tomcat.roz53.lab.etn.com/git-web/?p=core.git;a=blob_plain;f=tools/initdb.sql;hb=HEAD" |  mysql -u root
# wget -O - "http://tomcat.roz53.lab.etn.com/git-web/?p=core.git;a=blob_plain;f=tools/load_data.sql;hb=HEAD" | mysql -u root box_utf8
# wget -O - "http://tomcat.roz53.lab.etn.com/git-web/?p=core.git;a=blob_plain;f=tools/load_ROZLAB.sql;hb=HEAD" | mysql -u root box_utf8
cat /mysqldump | mysql -u root box_utf8
rm /mysqldump
/usr/lib/mysql/rcmysql stop
EOF

sed -i 's|exit.*|systemctl restart ssh|' etc/rc.local

# mv /srv/libvirt/rootfs/demo/usr/share/bios-web /srv/libvirt/rootfs/demo/usr/share/bios-web.x.$$; rsync -avPHK bios-backup:/export/DUMP/manual/test-debian/fullroot/srv/libvirt/.zfs/snapshot/20150212-0000/rootfs/demo/usr/share/bios-web/ /srv/libvirt/rootfs/demo/usr/share/bios-web/

virsh -c lxc:/// start demo

