
RFC-Thresholds  -  Thresholds protocol
====================================
Connects THRESHOLDS-USER peer to THRESHOLDS-EVALUATOR peer.

The THRESHOLDS-USER peer sends one of the following messages using MAILBOX SEND to THRESHOLDS-EVALUATOR peer:

. LIST - request list of tresholds
. ADD/json - add (create/update) new treshold

where '/' indicates a multipart string message, 'json' is valid json
document(1) and 'subject' of the message is "rfc-thresholds".

The THRESHOLDS-EVALUATOR peer MUST send the appropriate message message back to THRESHOLDS-USER peer using MAILBOX SEND:

. LIST/threshold_1[/threshold_2]...[/threshold_N]
. OK/json
. ERROR/reason

where '/' indicates a multipart string message, 'josn' is valid json document(1),
'reason' is error string and 'subject' of the message is "rfc-thresholds".


(1)
{
  "rule_name"   :  "<threshold_name>",
  "severity"    :  "<severity>",
  "metric"      :  "<metric_name>",
  "type"        :  "<type>",
  "element"     :  "<element_name>",
  "value"       :  "<value>",
  "action"      :  ["<action_1", ..., "<action_N>"]
}

