#!/bin/sh
#
# Copyright (C) 2015-2016 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    bios-networking
#  \brief   Helper script for networking part of REST API /admin/systemctl
#  \author  Michal Vyskocil <MichalVyskocil@Eaton.com>
#  \details Helper script for networking part of REST API /admin/systemctl
#           Really calling networking services synchronously is not possible
#           as changes in network config tends to close connection, therefore
#           the REST API call would never reply to caller.
#           This script is called by systemd via "bios-networking.service",
#           thus not running in webserver context, which can report success
#           using the old HTTP(S) connection.

# to ensure REST API call at least replies before actually changing the network
sleep 3
# On production boxes we have 2 or 3 renamed LAN interfaces
for L in 1 2 3 ; do ( ifdown --force LAN$L ; sleep 5; ifup --force LAN$L ) & done
# Support not-remapped devices, including those in a container environment
# and/or hot-plugged devices in USB ports
for L in 0 1 2 3 ; do ( ifdown --force eth$L ; sleep 5; ifup --force eth$L ) & done
wait
/bin/systemctl restart networking.service
/bin/systemctl restart ifplugd.service
