#!/bin/sh

#
# Copyright (C) 2015 - 2020 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    check_bios_license
#  \brief   Trivial verification script for REST API /admin/license
#  \author  Michal Vyskocil <MichalVyskocil@Eaton.com>
#  \author  Michal Hrusecky <MichalHrusecky@Eaton.com>


if [ -n "`wget -O - 'http://localhost/api/v1/admin/license/status' | grep '.*accepted.*yes.*'`" ]; then
	echo "License Accepted"
	exit 0
else
	echo "License Not Accepted"
	exit 1
fi
