#!/bin/bash

#
# Copyright (C) 2016 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#! \file verify-fs.sh
#  \author Jim Klimov <EvgenyKlimov@Eaton.com>
#  \author Michal Vyskocil <MichalVyskocil@Eaton.com>
#  \brief  Compress the previously rotated logs under LOGDIR
#

die ()
{
    echo "E: `date`: ${@}"
    exit 1
}

LANG=C
LC_ALL=C
TZ=UTC
export LANG LC_ALL TZ
umask -S 0027

# TODO: Should these be settable via service envvars (/etc/default/bios*)?
LOGDIR="/var/log"
EXTWIP="__WRITING__"
EXTARCH="bz2"
CMDARCH="bzip2 -c -9"

set -o pipefail || true

cd "$LOGDIR" || exit $?
echo "`date`: $0 starting in `pwd`" >&2

(
    flock -w 30 -x 200 || die "Can't aquire lock /run/biospath-compress-logs.logs"

    # move commpressed files
    rm -f messages.5.${EXTARCH}
    for i in $(seq 4 -1 1); do
        [[ -f messages.${i}.${EXTARCH} ]] || continue
        mv  messages.${i}.${EXTARCH} \
            messages.$((i+1)).${EXTARCH}
        chown root:adm messages.$((i+1)).${EXTARCH}
        chmod 0640 messages.$((i+1)).${EXTARCH}
    done

    ${CMDARCH} messages.1 > messages.1.${EXTARCH}
    chown root:adm messages.1.${EXTARCH}
    chmod 0640 messages.1.${EXTARCH}
) 200>/run/biospath-compress-logs.lock
