#!/usr/bin/env bash

img_type=$(cat /etc/bios-release.json | grep osimage-img-type)
if [[ $img_type = *"devel"* ]]
then
   #only for deploy
   exit 1
fi

if [ $# -ne 0 ] && [ $# -ne 2 ]
then
    #error
    exit 1
fi

if [ $# -eq 2 ] && [ $1 == "-t" ]
then
    sleep $2m
fi

echo "Root shell removed"
#usermod -s /usr/sbin/nologin root
rm -f /tmp/.rootpwd
