#!/usr/bin/env bash
#
# Copyright (C) 2018 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    disable-root-account
#  \brief   Helper script for locking the root account after EULA
#  \author  Lilian Barraud <lilianbarraud@Eaton.com>
#

JSONSH="/usr/share/fty/scripts/JSON.sh"
get_a_string_arg() { "$JSONSH" -x "$1" | (IFS="`printf '\t'`" read K V; echo "$V") | sed 's,^"\(.*\)",\1,' ; }
J="/etc/release-details.json"
img_type="$(get_a_string_arg osimage-img-type < $J)"

if [[ $img_type = *"devel"* ]]
then
   #only for deploy
   exit 0
fi

if [ $# -ne 0 ] && [ $# -ne 2 ]
then
    #error
    exit 1
fi

if [ $# -eq 2 ] && [ $1 == "-t" ]
then
    sleep ${2}m
fi

echo "Root shell removed"
#usermod -s /usr/sbin/nologin root
rm -f /tmp/.rootpwd
