#!/bin/bash
#
# Copyright (C) 2018 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    enable-root-account
#  \brief   Helper script for temporarily unlocking the root
#           account blocked after EULA
#  \author  Lilian Barraud <lilianbarraud@Eaton.com>
#

JSONSH="/usr/share/fty/scripts/JSON.sh"
get_a_string_arg() { "$JSONSH" -x "$1" | (IFS="`printf '\t'`" read K V; echo "$V") | sed 's,^"\(.*\)",\1,' ; }
J="/etc/release-details.json"
img_type="$(get_a_string_arg osimage-img-type < $J)"

umask 077

ROOT_PASSWORD_LOCATION=/tmp/.rootpwd

if [[ $img_type = *"devel"* ]]
then
   #only for deploy
   exit 1
fi

if [ -f $ROOT_PASSWORD_LOCATION ]
then
  #previous password still valid
  exit 1
fi

if [ $(id -u) -ne 0 ]
then
    exit 1
fi


ROOT_PASSWORD=$(dd if=/dev/urandom bs=9 count=1 2>/dev/null | base64)
echo "$ROOT_PASSWORD" > "$ROOT_PASSWORD_LOCATION"

echo "Root shell enabled and password changed"
#echo "root:$ROOT_PASSWORD" | chpasswd
#usermod -s /bin/bash root

/usr/libexec/fty/disable-root-account -t 60 &
