#!/bin/bash

umask 077

ROOT_PASSWORD_LOCATION=/tmp/.rootpwd

img_type=$(cat /etc/bios-release.json | grep osimage-img-type)
if [[ $img_type = *"devel"* ]]
then
   #only for deploy
   exit 1
fi

if [ -f $ROOT_PASSWORD_LOCATION ]
then
  #previous password still valid
  exit 1
fi

if [ $(id -u) -ne 0 ]
then
    exit 1
fi


ROOT_PASSWORD=$(dd if=/dev/urandom bs=9 count=1 2>/dev/null | base64)
echo "$ROOT_PASSWORD" > "$ROOT_PASSWORD_LOCATION"

echo "Root shell enabled and password changed"
#echo "root:$ROOT_PASSWORD" | chpasswd
#usermod -s /bin/bash root

/usr/libexec/fty/disable-root-account -t 60 &
