#!/bin/bash
#
# Copyright (C) 2015 - 2020 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Trick to rename the script in "ps" output, so "pidof" can find it
[ -z "${_SHELL_EXECED-}" ] && _SHELL_EXECED=yes exec -a "$0" /bin/bash < "$0"

while true; do
generate_measurement "`hostname -f`" temperature.THF "C" "`expr 17 + $RANDOM % 15`"
generate_measurement "`hostname -f`" humidity.THF    "%" "`expr 45 + $RANDOM % 35`"
sleep 55
done
