#!/bin/bash

# TODO: GPL

# Tool to setup routing on 42ity
# Author: Michal Vyskocil <michalvyskocil@eaton.com>
#

set -x
die () {
    echo "FATAL: ${@}" >&2
    exit 1
}

# Execute augtool with given arguments
augtool () {

    if [[ "${1}" == "set" ]]; then
        cat <<EOF | /usr/bin/sudo /usr/bin/augtool -S -I/usr/share/fty/lenses/
"${1}" "${2}" "${3}"
save
EOF
    elif [[ "${1}" == "rm" ]]; then
        cat <<EOF | /usr/bin/sudo /usr/bin/augtool -S -I/usr/share/fty/lenses/
"${1}" "${2}"
save
EOF
    else
        /usr/bin/sudo /usr/bin/augtool -S -I/usr/share/fty/lenses/ "${@}"
    fi
}

# Return augeas index
ag_index () {
    local cmd pattern
    cmd=${1}
    pattern=${2}

    augtool "${cmd}" | grep "= ${pattern}$" | cut -d '=' -f 1 | sed 's/ //g'
}

### MAIN ###
COMMAND=${@}
ARGS=("${@}")
LAST_IDX=$((${#} - 1))

# TODO: check add/del commands

# put all routing to the default interface, unless (dev)? iface_name is specified
# distinguish modes by checking last argument of post-up
IFACE_PATH=$(ag_index "match /files/etc/network/interfaces/iface[*]" "${ARGS[${LAST_IDX}]}")
if [[ -z "${IFACE_PATH}" ]]; then
    # iface[0] is lo
    IFACE_PATH="/files/etc/network/interfaces/iface[1]"
fi

#TODO: ^^^ tested until now!

case ${ARGS[0]} in
    add)
        augtool "set" "${IFACE_PATH}/post-up[last()+1]" "route ${COMMAND}"
        ;;
    del)
        POST_UP_PATH=$(ag_index "match ${IFACE_PATH}/post-up" "route ${COMMAND/del/add}")
        if [ -z "${POST_UP_PATH}" ]; then
            die "Can't delete non existent route ${COMMAND} from ${IFACE_PATH}"
        fi
        for line in ${POST_UP_PATH}; do
            augtool "rm" "${line}"
        done
        ;;
    *)
        die "Unknown command ${ARGS[0]}, use add/del"
esac
