#!/bin/sh

#
# Copyright (C) 2015 - 2021 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


#! \file   ifupdown-force
#  \author Jim Klimov <EvgenyKlimov@Eaton.com>
#  \author Based on Debian 8 packaged init-scripts
#  \brief  Stronger replacement for system ifupdown script
#  \detailed /etc/ifplugd/action.d/ifupdown-force "$IFACE" "$NEWSTATE"
# Enhanced for more reliable "down" actions compared to Debian8 default
# /etc/ifplugd/action.d/ifupdown and does not conflict on success nor fail

set -e

case "$2" in
up)
        # In some of the distros we use "ifup" tends to skip interfaces
        # that are not "UP" in the system. So make sure it is confgurable:
        /sbin/ifconfig "$1" "$2" || \
        /sbin/ip link set "$1" "$2"
        { /sbin/ifup "$1" && { /sbin/ip address show dev "$1" | egrep '^\s*inet\s+[0-9]+\.+[0-9]+\.+[0-9]+\.+[0-9]+/[0-9]+|^\s*inet6\s.*:.*/' ; } ; } || \
        /sbin/ifup --force "$1"
        ;;
down)
        /sbin/ifdown "$1" || \
        /sbin/ifdown --force "$1" || \
        /sbin/ifconfig "$1" "$2" || \
        /sbin/ip link set "$1" "$2"
        # By this point, at best the interface is not-configured,
        # at worst it is just "DOWN" and the system does not use it
        ;;
esac

