#!/bin/bash

#
# Copyright (C) 2019 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    rcmysql-transient
#  \brief   Helper script for fty-db-engine on newer distros
# \author Jim Klimov <EvgenyKlimov@Eaton.com>
# \details 
# For portability of the 42ity project, work with some database engine is
# abstracted into fty-db-engine.service unit, on which certain services
# depend and which can be implemented variably for several DB engines.
# The database engine is only enabled and initialized after EULA acceptance.
# For legacy reasons, work with mariadb/mysql goes by calling a script
# named /usr/lib/mysql/rcmysql which was available in the original distro
# packaging used by the product, but obsoleted with switch to Debian 10.
# This script enables the original service definition to wrap the abstract
# database management interactions while benefitting from the upstream
# development of that service directly, by managing a transient service.
#

# Fetched from https://blog.dhampir.no/content/sleeping-without-a-subprocess-in-bash-and-how-to-sleep-forever
# A sleep equivalent without subprocesses and lots of snoopy logging
snore()
{
    local IFS
    [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
    read ${1:+-t "$1"} -u $_snore_fd || :
}

case "$1" in
start)
    if [ ! -d /var/lib/mysql ]; then
        /usr/bin/mysql_install_db -u mysql || exit
    fi
    rm -rf /run/fty-db-engine/systemd || true
    mkdir -p /run/fty-db-engine/systemd || exit
    cp -f /lib/systemd/system/mariadb.service.orig /run/fty-db-engine/systemd/mariadb-transient.service \
    || cp -f /lib/systemd/system/mariadb.service /run/fty-db-engine/systemd/mariadb-transient.service \
    || exit
    sed -e 's,\(Alias.*=\),#\1,g' \
        -i /run/fty-db-engine/systemd/mariadb-transient.service
    cp -f /run/fty-db-engine/systemd/mariadb-transient.service /run/systemd/system/ || exit

    rm -rf /run/systemd/system/mariadb-transient.service.d || RES=$?
    mkdir -p /run/systemd/system/mariadb-transient.service.d || exit

    # Per https://mariadb.com/kb/en/systemd/?_ga=2.157713337.2042007370.1575907190-1147147581.1575907190#configuring-access-to-home-directories
    # so the service can use /root/.my.cnf
#    cat > /run/systemd/system/mariadb-transient.service.d/dontprotecthome.conf << EOF
#[Service]
#ProtectHome=false
#EOF

    /bin/systemctl daemon-reload
    /bin/systemctl enable --runtime mariadb-transient.service || exit
    /bin/systemctl start mariadb-transient.service

    # All hail systemd... for some reason, PartOf works if we restart very soon
    # after the couple of services is started; but after a minute expires, a
    # `systemctl stop mariadb-transient` no longer propagates to fty-db-engine.
    cat > /run/systemd/system/mariadb-transient.service.d/fty-db-engine.conf << EOF
[Unit]
PartOf=fty-db-engine.service

[Service]
ExecStopPost=/bin/systemctl stop --no-block fty-db-engine.service

[Install]
RequiredBy=fty-db-engine.service
WantedBy=fty-db-engine.service
EOF
    /bin/systemctl daemon-reload

    # The fty-db-engine expects a forked child
    ( ( while /bin/systemctl is-active mariadb-transient.service >/dev/null \
        && [[ -s /run/fty-db-engine/systemd/mariadb-transient.service ]] \
        ; do
            # Easily breakable sleep loop
            for A in {1..60} ; do snore 1 || exit ; done
        done ; )
        echo "$0 $* finished `date -u`: mariadb-transient.service is no more" >&2
        /bin/systemctl is-active mariadb-transient.service >&2
     ) &
    ;;
stop)
    RES=0
    rm -f /run/fty-db-engine/systemd/mariadb-transient.service || RES=$?
    /bin/systemctl stop mariadb-transient.service || RES=$?
    /bin/systemctl disable --runtime mariadb-transient.service || RES=$?
    rm -rf /run/systemd/system/mariadb-transient.service.d || RES=$?
    rm -f /run/systemd/system/mariadb-transient.service || RES=$?
    /bin/systemctl daemon-reload
    exit $RES
    ;;
status)
    /bin/systemctl status mariadb-transient.service fty-db-engine.service fty-db-init.service
    ;;
*)  echo "Unknown argument: $1" >&2
    exit 1
    ;;
esac
