#!/bin/sh

#
# Copyright (C) 2015 - 2020 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#! \file   ssl-create.sh
#  \author Michal Hrusecky <MichalHrusecky@Eaton.com>
#  \author Jim Klimov <EvgenyKlimov@Eaton.com>
#  \brief  Initialize webserver X509 certificate
#  \details Prepares a new self-signed certificate if one is missing
#           or has expired or is not yet valid or is for another host.
#           Does not replace CA-issued certs, even if they seem invalid.

CN=""
FROM=""
TO=""
SIG="Autogenerated self-signed"

PEM_FINAL_CERT="/etc/tntnet/bios.pem"
PEM_KEY="/etc/tntnet/bios.key"
PEM_CERT="/etc/tntnet/bios.crt"

# Warn about expiration this much in advance, e.g. 45 days
WARN_EXPIRE="`expr 45 \* 24 \* 3600`"

TS_NOW="`TZ=UTC date -u +%s`"
LOCAL_HOSTNAME="`hostname -f`" || LOCAL_HOSTNAME=""
if [ -z "$LOCAL_HOSTNAME" ] || [ "$LOCAL_HOSTNAME" = localhost ] ; then
	LOCAL_HOSTNAME="`hostname`" || LOCAL_HOSTNAME=""
fi
[ -z "$LOCAL_HOSTNAME" ] && LOCAL_HOSTNAME="`cat /etc/hostname`"

if [ -z "$LOCAL_HOSTNAME" ]; then
	echo "ERROR: can't guess hostname" >&2
	exit 1
fi

BIOS_USER="admin"

CERT_LOADABLE=no
if [ -f "${PEM_FINAL_CERT}" ] ; then
    # The command below can report errors if the file is empty or unreadable
    # so we do not test '-r' nor '-s' above explicitly.
    SSL_OUT="`openssl x509 -noout -dates -subject < "${PEM_FINAL_CERT}"`" && \
    [ -n "$SSL_OUT" ] && CERT_LOADABLE=yes
fi

if [ "$CERT_LOADABLE" = yes ]; then
    FROM="`echo "$SSL_OUT" | sed -n 's|notBefore=||p'`" && \
        [ -n "$FROM" ] && FROM="`TZ=UTC date -u -d "$FROM" +%s`" || \
        FROM=""
    TILL="`echo "$SSL_OUT" | sed -n 's|notAfter=||p'`" && \
        [ -n "$TILL" ] && TILL="`TZ=UTC date -u -d "$TILL" +%s`" && \
        [ "$TILL" -gt "$WARN_EXPIRE" ] && TILL="`expr $TILL - $WARN_EXPIRE`" || \
        TILL=""
    CN="`echo "$SSL_OUT" | sed -n 's|subject= /CN=||p'`" || \
        CN=""
fi

if [ ! -r "${PEM_FINAL_CERT}" ] || [ ! -s "${PEM_FINAL_CERT}" ] || \
   [ -z "$FROM" ] || [ -z "$TILL" ] || \
   [ "$FROM" -gt "${TS_NOW}" ] || [ "$TILL" -lt "${TS_NOW}" ] || \
   [ "$CN" != "${LOCAL_HOSTNAME}" ] \
; then
    # Not to overwrite CA-issued certificate
    if [ -s "${PEM_FINAL_CERT}" ] && [ -z "`grep "$SIG" "${PEM_FINAL_CERT}" 2>/dev/null`" ]; then
        chown "${BIOS_USER}" "${PEM_FINAL_CERT}"        # Just in case
        [ "$CERT_LOADABLE" = yes ]      # Error out if the cert file is invalid
                                        # (reported to stderr by openssl above)
        exit $?
    fi

    # certificate configuration (disable CA)
    echo "[ req ]" > /run/tntnet-bios/ssl.conf
    echo "distinguished_name=dn" >> /run/tntnet-bios/ssl.conf
    echo "[ dn ]" >> /run/tntnet-bios/ssl.conf
    echo "[ ext ]" >> /run/tntnet-bios/ssl.conf
    echo "basicConstraints=CA:FALSE" >> /run/tntnet-bios/ssl.conf

    # Generate self-signed cert with a new key and other data
    openssl req -config /run/tntnet-bios/ssl.conf -x509 -sha256 -newkey rsa:2048 \
        -keyout "${PEM_KEY}" -out "${PEM_CERT}" \
        -days 9125 -nodes -subj "/CN=${LOCAL_HOSTNAME}" \
    || exit $?

    rm /run/tntnet-bios/ssl.conf

    rm -f "${PEM_FINAL_CERT}"
    echo "$SIG" | \
        cat - "${PEM_KEY}" "${PEM_CERT}" > "${PEM_FINAL_CERT}" \
    || exit $?

    chown "${BIOS_USER}" "${PEM_FINAL_CERT}"
    chown "${BIOS_USER}:www-data" "${PEM_KEY}"
    chmod 640 "${PEM_KEY}"
    chown "${BIOS_USER}:www-data" "${PEM_CERT}"
    chmod 644 "${PEM_CERT}"

    exit $?
fi

exit 0
