#!/bin/sh
CN=""
FROM=""
TO=""
SIG="Autogenerated self-signed"
if [ -f /etc/tntnet/bios.pem ]; then
    SSL_OUT="`cat /etc/tntnet/bios.pem | openssl x509 -noout -dates -subject`"
    FROM="`echo "$SSL_OUT" | sed -n 's|notBefore=||p'`"
    [ -z "$FROM" ] || FROM="`date -d "$FROM" +%s`"
    TO="`echo "$SSL_OUT" | sed -n 's|notAfter=||p'`"
    [ -z "$FROM" ] || TO="`date -d "$TO" +%s`"
    CN="`echo "$SSL_OUT" | sed -n 's|subject= /CN=||p'`"
fi
if [ \! -r /etc/tntnet/bios.pem ]  || [ $FROM -gt `date +%s` ] || \
   [ $TO -lt `date +%s` ]          || [ $CN \!= `hostname` ]; then
    # Not to overwrite correct certificate
    if [ -r /etc/tntnet/bios.pem ] && [ -z "`grep "$SIG" /etc/tntnet/bios.pem 2> /dev/null`" ]; then
        exit 0
    fi
    openssl req -x509 -newkey rsa:2048 -keyout /tmp/key.pem -out /tmp/cert.pem -days 365 -nodes -subj "/CN=`hostname`"
    echo "$SIG" | \
    cat - /tmp/key.pem /tmp/cert.pem > /etc/tntnet/bios.pem
    rm /tmp/key.pem /tmp/cert.pem
    chown admin /etc/tntnet/bios.pem
fi
