#!/bin/bash
# Copyright (C) 2017 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file   start-db-services
#  \brief  Start and enable all services dependent on bios-db-init/fty-db-init service
#  \author Michal Vyskocil <michalvyskocil@eaton.com>

die () {
    echo "ERROR: ${@}" >&2
    exit 1
}

if [[ -f /etc/default/bios-db-rw ]]; then
    echo "SKIPPED: /etc/default/bios-db-rw exists"
    exit 0
fi

sudo /bin/systemctl start fty-db-firstboot || die "Starting fty-db-firstboot failed"

sleep 2
if [[ ! -f /etc/default/bios-db-rw ]]; then
    echo "ERROR: /etc/default/bios-db-rw is missing"
    exit 1
fi

sudo /bin/systemctl enable fty-db-init || die "Enabling fty-db-init failed"
sudo /bin/systemctl enable mysql || die "Enabling mysql failed"

for DIR in /lib/systemd/system /usr/lib/systemd/system /run/systemd/system /etc/systemd/system/; do
    if [[ ! -d "${DIR}" ]]; then
        continue
    fi

    grep 'Requires.*bios-db-init.service' "${DIR}"/*.service 2>/dev/null | cut -d ':' -f 1 | xargs -L1 basename 2>/dev/null | while read SERVICE; do
        echo "INFO: enable and start ${SERVICE}"
        sudo /bin/systemctl enable "${SERVICE}"
        sudo /bin/systemctl start "${SERVICE}"
    done
done
